import Head from 'next/head';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { useEffect, useState } from 'react';
import type { GraphData, SearchIndex } from '@/lib/attack/types';
import { AttackProvider } from '@/lib/attack/context';
import AppShell from '@/components/attack/AppShell';
import FilterSidebar from '@/components/attack/FilterSidebar';

// R3F (React Three Fiber) is client-only, so we disable SSR for the Scene component.
// This prevents hydration errors since Three.js relies on browser APIs (WebGL, canvas).
const Scene = dynamic(() => import('@/components/attack/Scene'), { ssr: false });

// Shape of the state once both JSON files have been fetched successfully.
interface LoadedState {
  graph: GraphData;
  searchIndex: SearchIndex;
}

/**
 * Full-bleed application page for the ATT&CK 3D Explorer.
 *
 * This page intentionally skips the default site Layout (navbar, footer, etc.)
 * so the 3D canvas can fill the entire viewport. It fetches the pre-built static
 * JSON files on mount, then renders the scene wrapped in the global context
 * provider and the AppShell layout (sidebar + canvas + detail panel).
 *
 * Per-page layout opt-out: attaching getLayout = (page) => page tells _app.js
 * to skip the default Layout wrapper for this route.
 */
export default function AttackExplorerApp() {
  // Holds both data blobs once they have loaded, or null while loading.
  const [loaded, setLoaded] = useState<LoadedState | null>(null);
  // Holds a human-readable error string if either fetch fails.
  const [error, setError] = useState<string | null>(null);

  // Fetch the two static JSON data files in parallel on first mount.
  // These are generated by the build script and served from /public/data/.
  useEffect(() => {
    Promise.all([
      fetch('/data/attack-graph.json').then(r => r.json()),
      fetch('/data/attack-index.json').then(r => r.json()),
    ])
      .then(([graph, searchIndex]) => setLoaded({ graph, searchIndex }))
      .catch(err => setError(String(err)));
  }, []);

  return (
    <>
      <Head>
        <title>ATT&amp;CK 3D Explorer</title>
        <meta name="description" content="Interactive 3D explorer of MITRE ATT&CK Enterprise." />
        <link rel="icon" href="/favicon.ico" />
        {/* Remove default body margin/padding and prevent scrollbars on the 3D canvas page. */}
        <style>{`html, body { margin: 0; padding: 0; overflow: hidden; }`}</style>
      </Head>

      {/* Back-navigation link fixed to top-right, always above the 3D canvas (z-50). */}
      <Link
        href="/lab/attack-explorer"
        className="fixed top-3 right-3 z-50 text-xs text-medteal hover:text-lightteal bg-darkblue/80 px-3 py-2 rounded border border-darkteal/40"
      >
        &larr; Back to project page
      </Link>

      {/* Error state: data fetch failed. Shown instead of the canvas. */}
      {error && (
        <div className="fixed inset-0 flex items-center justify-center bg-darkblue text-red-300">
          Failed to load ATT&amp;CK data: {error}
        </div>
      )}

      {/* Loaded state: render the full 3D explorer. */}
      {loaded && (
        <AttackProvider graph={loaded.graph} searchIndex={loaded.searchIndex}>
          {/* AppShell manages the sidebar + canvas + detail panel layout. */}
          <AppShell
            sidebar={<FilterSidebar />}
            canvas={<Scene />}
            detailPanel={<div className="p-4 text-sm text-lightteal/60">Details panel coming in Phase 4...</div>}
            detailPanelOpen={false}
          />
        </AttackProvider>
      )}

      {/* Loading state: shown while the JSON fetches are in flight. */}
      {!loaded && !error && (
        <div className="fixed inset-0 flex items-center justify-center bg-darkblue text-lightteal/60">
          Loading ATT&amp;CK data...
        </div>
      )}
    </>
  );
}

// Opt out of the default site Layout for this full-bleed page.
// _app.js reads this property and skips wrapping with Layout/Navbar/Footer.
AttackExplorerApp.getLayout = (page: React.ReactElement) => page;
